### ISSUE TITLE
[Console] Errors on console

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1114]
Observing repeated errors on console during testathon 20160808:

```
main.js:3 Error: [$rootScope:inprog] http://errors.angularjs.org/1.4.4/$rootScope/inprog?p0=%24digest
    at Error (native)
    at https://hulk.arc.nasa.gov:8080/main.js:1:21188
    at f (https://hulk.arc.nasa.gov:8080/main.js:3:17432)
    at p.$apply (https://hulk.arc.nasa.gov:8080/main.js:3:21481)
    at https://hulk.arc.nasa.gov:8080/main.js:14:23017
    at https://hulk.arc.nasa.gov:8080/main.js:14:22622
    at Array.forEach (native)
    at i.value (https://hulk.arc.nasa.gov:8080/main.js:14:22602)
    at p.$digest (https://hulk.arc.nasa.gov:8080/main.js:3:20049)
    at p.$apply (https://hulk.arc.nasa.gov:8080/main.js:3:21570)
```

Haven't determined what triggers these errors yet.

**Comment by akhenry** [comment]
Error is being thrown here - https://github.com/nasa/openmct/blob/master/platform/commonUI/general/src/directives/MCTTree.js#L32

**Comment by VWoeltjen** [comment]
Ah! That should be reasonably straightforward then. Comes from #1100

**Comment by VWoeltjen** [comment]
Verified in testathon 2016-09-19

**Comment by charlesh88** [comment]
Testathon 2016-09-19: verified (I guess) - no console errors observed.

**Comment by larkin** [comment]
Testathon 2016-10-21: No console errors observed, looks like this was resolved previously.
