### ISSUE TITLE
Integration Tutorial fails with recent OpenMCT (http is not defined)

### ISSUE THREAD

**Issue by fsmunoz** [nasa/openmct#1749]
Hello,

I've tried to followed the integration tutorial at https://github.com/nasa/openmct-tutorial with a recent OpenMCT pull and it fails with:

~~~
ReferenceError :8080/bower_components/angular/angular.min.js:107 ReferenceError: http is not defined
    at getDictionary (http://localhost:8080/dictionary-plugin.js:2:5)
    at Object.get (http://localhost:8080/dictionary-plugin.js:10:16)
    at ObjectAPI.(anonymous function) [as get] (http://localhost:8080/src/api/objects/ObjectAPI.js:156:37)
    at MissingModelCompatibilityDecorator.<anonymous> (http://localhost:8080/src/adapter/services/MissingModelCompatibilityDecorator.js:56:41)
    at Array.map (native)
    at MissingModelCompatibilityDecorator.apiFetch (http://localhost:8080/src/adapter/services/MissingModelCompatibilityDecorator.js:50:28)
    at MissingModelCompatibilityDecorator.<anonymous> (http://localhost:8080/src/adapter/services/MissingModelCompatibilityDecorator.js:82:29)
    at http://localhost:8080/bower_components/angular/angular.min.js:118:217
    at n.$eval (http://localhost:8080/bower_components/angular/angular.min.js:133:39)
    at n.$digest (http://localhost:8080/bower_components/angular/angular.min.js:130:60)
~~~

This is in the step 3 (https://github.com/nasa/openmct-tutorial#step-3---providing-objects).

Not sure if this is something broken in my setup or if it stems from changes in the API (I'm assuming this tutorial uses the new API, at least that's what it looks like but not knowing the previous one it's not absolutely clear).

Using the openmct-tutorial by itself works though, it's only when using the latest version of OpenMCT with the code from the tutorial.

## Versions
* OpenMCT: latest commit is 7f43c0bf1a5f9344a9c8803b35e81d56c773e99a

* Node
~~~
$ node -v
v7.10.1
~~~

* OS
~~~
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.3 (Maipo)
$ uname -a
Linux aldebaran 3.10.0-514.26.2.el7.x86_64 #1 SMP Fri Jun 30 05:26:04 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
~~~

**Comment by fsmunoz** [comment]
... and it was my fault, I assumed that `http` was something standard in AngularJS or in some other OpenMCT required lib, just noticed the 

>  <script src="lib/http.js"></script>

include in `index.html` in the tutorial. Closing.
