### ISSUE TITLE
clean npm install issue

### ISSUE THREAD

**Issue by tmar89** [nasa/openmct#2413]
Did npm install, with set strict-ssl false because it doesn't work if true, and I keep getting this token error. Just following the instructions since I'm new to this.

Edit: This is from the openmct-tutorial package, but it still happens with the openmct package as well.

```
> webpack-cli@3.3.2 postinstall /usr/OpenMCT/openmct-tutorial/node_modules/openmct/node_modules/painterro/node_modules/webpack-cli
> node ./bin/opencollective.js


/usr/OpenMCT/openmct-tutorial/node_modules/openmct/node_modules/painterro/node_modules/webpack-cli/bin/opencollective.js:12
function print(str = "", color = "dim") {
                   ^
SyntaxError: Unexpected token =
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by tmar89** [comment]
Needed to upgrade node/npm
