### ISSUE TITLE
Error on running npm install on my mac

### ISSUE THREAD

**Issue by ptc-ddahan** [nasa/openmct#2443]
Hi,

This is the first time installing openmct. 
I installed the latest stable version of Node.JS and updated npm.

When running `npm install` I get the following error:
```
ddahan1ml:openmct ddahan$ npm install

> openmct@0.14.0-SNAPSHOT prepare /Users/ddahan/git/openmct
> node ./node_modules/bower/bin/bower install && node ./node_modules/gulp/bin/gulp.js install

[20:51:05] Using gulpfile ~/git/openmct/gulpfile.js
[20:51:05] Starting 'stylesheets'...
[20:51:05] Starting 'scripts'...
[20:51:05] Optimizing openmct.js
{ Error: Parse error using esprima for file: /Users/ddahan/git/openmct/node_modules/painterro/build/painterro.min.js
Error: Line 258: Unexpected token *
    at /Users/ddahan/git/openmct/node_modules/requirejs/bin/r.js:29563:47
    at /Users/ddahan/git/openmct/node_modules/requirejs/bin/r.js:3063:37
    at /Users/ddahan/git/openmct/node_modules/requirejs/bin/r.js:3011:25
    at Function.prim.nextTick (/Users/ddahan/git/openmct/node_modules/requirejs/bin/r.js:29929:9)
    at Object.callback (/Users/ddahan/git/openmct/node_modules/requirejs/bin/r.js:3010:26)
    at Object.then (/Users/ddahan/git/openmct/node_modules/requirejs/bin/r.js:3060:23)
    at /Users/ddahan/git/openmct/node_modules/requirejs/bin/r.js:29548:36
    at /Users/ddahan/git/openmct/node_modules/requirejs/bin/r.js:3063:37
    at /Users/ddahan/git/openmct/node_modules/requirejs/bin/r.js:3011:25
    at Function.prim.nextTick (/Users/ddahan/git/openmct/node_modules/requirejs/bin/r.js:29929:9)
  fileName:
   '/Users/ddahan/git/openmct/node_modules/painterro/build/painterro.min.js' }

events.js:174
      throw er; // Unhandled 'error' event
```
Daniel

**Comment by nttoole** [comment]
Had the same issue but found some manual steps to resolve it (for now): https://stackoverflow.com/questions/57495208/how-to-fix-parse-error-installing-open-mct

**Comment by ptc-ddahan** [comment]
Thanks @nttoole ! 
That worked out for me.
