### ISSUE TITLE
Getting error while trying to install modules

### ISSUE THREAD

**Issue by egmed** [nasa/openmct#2663]
I'm trying to install and run [Open Mct][1].

In the [getting started page][2] they ask to: 
1. clone the repository "git clone https://github.com/nasa/openmct.git"
2. npm install
3. npm start

When i'm trying to "npm install" i get some errors.
i tried it in 2 different computers and both ended up having the same following error:   

    PS C:\code\openmct> npm install
    
    > openmct@1.0.0-snapshot prepare C:\code\openmct
    > npm run build:prod
    
    
    > openmct@1.0.0-snapshot build:prod C:\code\openmct
    > cross-env NODE_ENV=production webpack
    
    Hash: 77a6c86a519d4235aa9f
    Version: webpack 4.41.5
    Time: 14777ms
    Built at: 02/10/2020 4:09:54 PM
     11 assets
    Entrypoint openmct = openmct.js openmct.js.map
    Entrypoint espressoTheme = espressoTheme.js espressoTheme.js.map
    Entrypoint snowTheme = snowTheme.js snowTheme.js.map
    Entrypoint maelstromTheme = maelstromTheme.js maelstromTheme.js.map
    
    ERROR in ./src/plugins/themes/espresso-theme.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
    Error: import file cannot be resolved: "@import "~styles/vendor/normalize-min";" @C:\code\openmct\src\plugins\themes\espresso-theme.scss
        at Object.importReplacer (C:\code\openmct\node_modules\fast-sass-loader\lib\index.js:206:19)
        at importReplacer.throw (<anonymous>)
        at onRejected (C:\code\openmct\node_modules\co\index.js:81:24)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:94:5)
        at C:\code\openmct\node_modules\webpack\lib\NormalModule.js:316:20
        at C:\code\openmct\node_modules\loader-runner\lib\LoaderRunner.js:367:11
        at C:\code\openmct\node_modules\loader-runner\lib\LoaderRunner.js:233:18
        at context.callback (C:\code\openmct\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at C:\code\openmct\node_modules\fast-sass-loader\lib\index.js:311:5
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:94:5)
    
    ERROR in ./src/plugins/themes/maelstrom-theme.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
    Error: import file cannot be resolved: "@import "~styles/vendor/normalize-min";" @C:\code\openmct\src\plugins\themes\maelstrom-theme.scss
        at Object.importReplacer (C:\code\openmct\node_modules\fast-sass-loader\lib\index.js:206:19)
        at importReplacer.throw (<anonymous>)
        at onRejected (C:\code\openmct\node_modules\co\index.js:81:24)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:94:5)
        at C:\code\openmct\node_modules\webpack\lib\NormalModule.js:316:20
        at C:\code\openmct\node_modules\loader-runner\lib\LoaderRunner.js:367:11
        at C:\code\openmct\node_modules\loader-runner\lib\LoaderRunner.js:233:18
        at context.callback (C:\code\openmct\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at C:\code\openmct\node_modules\fast-sass-loader\lib\index.js:311:5
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:94:5)
    
    ERROR in ./src/plugins/themes/snow-theme.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
    Error: import file cannot be resolved: "@import "~styles/vendor/normalize-min";" @C:\code\openmct\src\plugins\themes\snow-theme.scss
        at Object.importReplacer (C:\code\openmct\node_modules\fast-sass-loader\lib\index.js:206:19)
        at importReplacer.throw (<anonymous>)
        at onRejected (C:\code\openmct\node_modules\co\index.js:81:24)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:94:5)
        at C:\code\openmct\node_modules\webpack\lib\NormalModule.js:316:20
        at C:\code\openmct\node_modules\loader-runner\lib\LoaderRunner.js:367:11
        at C:\code\openmct\node_modules\loader-runner\lib\LoaderRunner.js:233:18
        at context.callback (C:\code\openmct\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at C:\code\openmct\node_modules\fast-sass-loader\lib\index.js:311:5
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:94:5)
    Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/fast-sass-loader/lib/index.js!src/plugins/themes/espresso-theme.scss:
        Entrypoint mini-css-extract-plugin = *
    
        ERROR in ./src/plugins/themes/espresso-theme.scss (./node_modules/css-loader!./node_modules/fast-sass-loader/lib!./src/plugins/themes/espresso-theme.scss)
        Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
        Error: import file cannot be resolved: "@import "~styles/vendor/normalize-min";" @C:\code\openmct\src\plugins\themes\espresso-theme.scss
            at Object.importReplacer (C:\code\openmct\node_modules\fast-sass-loader\lib\index.js:206:19)
            at importReplacer.throw (<anonymous>)
            at onRejected (C:\code\openmct\node_modules\co\index.js:81:24)
            at runMicrotasks (<anonymous>)
            at processTicksAndRejections (internal/process/task_queues.js:94:5)
    Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/fast-sass-loader/lib/index.js!src/plugins/themes/maelstrom-theme.scss:
        Entrypoint mini-css-extract-plugin = *
    
        ERROR in ./src/plugins/themes/maelstrom-theme.scss (./node_modules/css-loader!./node_modules/fast-sass-loader/lib!./src/plugins/themes/maelstrom-theme.scss)
        Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
        Error: import file cannot be resolved: "@import "~styles/vendor/normalize-min";" @C:\code\openmct\src\plugins\themes\maelstrom-theme.scss
            at Object.importReplacer (C:\code\openmct\node_modules\fast-sass-loader\lib\index.js:206:19)
            at importReplacer.throw (<anonymous>)
            at onRejected (C:\code\openmct\node_modules\co\index.js:81:24)
            at runMicrotasks (<anonymous>)
            at processTicksAndRejections (internal/process/task_queues.js:94:5)
    Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/fast-sass-loader/lib/index.js!src/plugins/themes/snow-theme.scss:
        Entrypoint mini-css-extract-plugin = *
    
        ERROR in ./src/plugins/themes/snow-theme.scss (./node_modules/css-loader!./node_modules/fast-sass-loader/lib!./src/plugins/themes/snow-theme.scss)
    
        ERROR in ./src/plugins/themes/snow-theme.scss (./node_modules/css-loader!./node_modules/fast-sass-loader/lib!./src/plugins/themes/snow-theme.scss)
        Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
        Error: import file cannot be resolved: "@import "~styles/vendor/normalize-min";" @C:\code\openmct\src\plugins\themes\snow-theme.scss
            at Object.importReplacer (C:\code\openmct\node_modules\fast-sass-loader\lib\index.js:206:19)
            at importReplacer.throw (<anonymous>)
            at onRejected (C:\code\openmct\node_modules\co\index.js:81:24)
            at runMicrotasks (<anonymous>)
            at processTicksAndRejections (internal/process/task_queues.js:94:5)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 2
    npm ERR! openmct@1.0.0-snapshot build:prod: `cross-env NODE_ENV=production webpack`
    npm ERR! Exit status 2
    npm ERR!
    npm ERR! Failed at the openmct@1.0.0-snapshot build:prod script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-02-10T14_09_54_865Z-debug.log
    npm ERR! code ELIFECYCLE
    npm ERR! errno 2
    npm ERR! openmct@1.0.0-snapshot prepare: `npm run build:prod`
    npm ERR! Exit status 2
    npm ERR!
    npm ERR! Failed at the openmct@1.0.0-snapshot prepare script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-02-10T14_09_54_905Z-debug.log

Anybody knows what is the problem?

Many thanks!

  [1]: https://nasa.github.io/openmct/
  [2]: https://nasa.github.io/openmct/getting-started/

**Comment by Srokap** [comment]
Same thing as #2604

**Comment by Kokodora** [comment]
Hey,
I had a quite similar error when installing on windows, I fixed it like that:
In the folder "openmct\src\plugins\themes" replace the paths from the *.scss files starting with "~stytles" with "../../styles"
With this change it also works on windows, maybe a good idea to change it in general.
Greetings

**Comment by unlikelyzero** [comment]
closed by https://github.com/nasa/openmct/pull/3361
