### ISSUE TITLE
[Bug] Viewing a plot in scrolling mode throws an error

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#295]
To reproduce:

1. Select a sine wave plot
1. Select 'scrolling' from the list of available views
1. The error below will appear in the javascript console:

```
TypeError: data.getPointCount is not a function
    at findCandidate (http://localhost:8080/platform/features/scrolling/src/ScrollingListPopulator.js:80:39)
    at Array.forEach (native)
    at getLatestDataValues (http://localhost:8080/platform/features/scrolling/src/ScrollingListPopulator.js:101:23)
    at ScrollingListPopulator.getRows (http://localhost:8080/platform/features/scrolling/src/ScrollingListPopulator.js:143:26)
    at getRows (http://localhost:8080/platform/features/scrolling/src/ScrollingListController.js:50:34)
    at updateRows (http://localhost:8080/platform/features/scrolling/src/ScrollingListController.js:56:43)
    at Object.setupColumns [as fn] (http://localhost:8080/platform/features/scrolling/src/ScrollingListController.js:124:17)
    at n.$digest (http://localhost:8080/platform/framework/lib/angular.min.js:130:310)
    at n.$apply (http://localhost:8080/platform/framework/lib/angular.min.js:133:330)
    at g (http://localhost:8080/platform/framework/lib/angular.min.js:87:340)
```

**Comment by akhenry** [comment]
The issue is defunct as the scrolling view has been retired in favour of tables. Closing.
