### ISSUE TITLE
[Snapshots] snapshot of folder object resulted in console error

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4012]
## Overview
Logged into deployment. Navigated to folder. Tried to take a snapshot and save to snapshot container. Could not replicate after initial error.

Error notification in UI.
Error in console (shown below).

## Expected Behavior
Snapshots should save to container.

## Steps to Reproduce
1. Snapshot
2. 😮 

```
17a9c0c0098 0ms Starting document clone
611:54:24.903 [Violation] Avoid using document.write(). <URL>
611:54:24.983 [Violation] 'message' handler took <N>ms
11:47:49.955 html2canvas.js:2377 17a9c0c0098 469ms Document cloned, using computed rendering
11:47:49.955 html2canvas.js:2377 17a9c0c0098 469ms Starting DOM parsing
11:47:50.178 html2canvas.js:2377 17a9c0c0098 692ms Added image data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'%3e%3cpath fill='%23000000' d='M448 96H288l-54.6-54.6-18.7-18.7C202.2 10.2 177.6 0 160 0H32C14.4 0 0 14.4 0 32v192c0-35.2 28.8-64 64-64h384c35.2 0 64 28.8 64 64
11:47:50.194 html2canvas.js:2377 17a9c0c0098 708ms Added image data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'%3e%3cpath fill='%23000000' d='M76 236.9c5.4-2.1 20.4-17.8 34.9-54.7C126.8 141.5 154.5 93 196 93c19.7 0 38 10.9 54.6 32.5 14 18.2 24.4 40.8 30.5 56.7 14.5 36.9 
11:47:50.223 html2canvas.js:2377 17a9c0c0098 737ms Added image data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'%3e%3cpath fill='%23000000' d='M128 128h192v64H128zM192 224h192v64H192zM160 320h192v64H160z'/%3e%3cpath fill='%23000000' d='M416 0h-64v96h63.8c.1 0 .1.1.2.2v319
11:47:50.230 html2canvas.js:2377 17a9c0c0098 744ms Added image data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'%3e%3cpath fill='%23000000' d='M415 0H97C43.65 0 0 43.65 0 97v203.41c7.09 9.32 12.83 14.17 16 15.42 7.14-2.81 27.22-23.77 46.48-73C83.71 188.64 120.64 124 176 1
11:47:50.262 html2canvas.js:2377 17a9c0c0098 775ms Starting renderer
11:47:50.262 html2canvas.js:2377 17a9c0c0098 776ms Canvas renderer initialized (922x648 at 307,71) with scale 2.5
11:47:50.312 openmct.js:284 error capturing image DOMException: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:304:156679
    at https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:304:1816
    at Object.next (https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:304:1921)
    at https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:304:1302
    at Object.next (https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:304:1921)
    at s (https://banner.ndc.nasa.gov/testathon/node_modules/openmct/dist/openmct.js:304:689)
11:47:50.319 snapshot.js:25 Uncaught (in promise) TypeError: Cannot destructure property 'blob' of 'undefined' as it is undefined.
    at Ue.<anonymous> (snapshot.js:25)
```

**Comment by unlikelyzero** [comment]
@davetsay I just attempted and could not reproduce
