### ISSUE TITLE
Example User test should cleanup login form

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#4886]
#### Summary
As part of [reenabling tests in the example directory](https://github.com/nasa/openmct/pull/4883/files#diff-8775189715d691c2a4379e8237603f818942ebbfbf2c5bc584601448b09380b5R1), the `exampleUser` plugin test was [disabled](https://github.com/nasa/openmct/pull/4883/files#diff-c3f0f1db67a5b6cec37c323a775143bc10608b08394fbddf9d684b5400ac8174R29). I suspect this is because the login form that the plugin adds is [added repeatedly to the DOM](https://github.com/nasa/openmct/blob/master/example/exampleUser/ExampleUserProvider.js#L99)
![image](https://user-images.githubusercontent.com/9853862/155097850-6e13f9ac-d55e-4046-a5a1-0af0f2d8115e.png)

This in turn causes plugin tests that assume absolute positioning to fail, e.g., the Menu API:
```
 Menu Placements
      ✗ default menu position BOTTOM_RIGHT (5ms)
	Error: Expected 141 to equal 16.
	    at <Jasmine>
	    at UserContext.eval (webpack-internal:///./src/api/menu/MenuAPISpec.js:198:25)
	    at <Jasmine>

      ✗ menu position BOTTOM_RIGHT (5ms)
	Error: Expected 141 to equal 16.
	    at <Jasmine>
	    at UserContext.eval (webpack-internal:///./src/api/menu/MenuAPISpec.js:214:25)
	    at <Jasmine>
```
#### Expected vs Current Behavior
All tests should pass with [example tests enabled](https://github.com/nasa/openmct/pull/4883/files#diff-8775189715d691c2a4379e8237603f818942ebbfbf2c5bc584601448b09380b5R1).
#### Steps to Reproduce
1. [Reenable example tests](https://github.com/nasa/openmct/pull/4883/files#diff-8775189715d691c2a4379e8237603f818942ebbfbf2c5bc584601448b09380b5R1)
2. Run `npm test`
3. Observe Menu API test failures

#### Environment

* Open MCT Version: master with example tests enabled
* Deployment Type: dev
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [X] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

**Comment by unlikelyzero** [comment]
Assigning to Jamie since he most recently looked at this test (according to slack) and mostly likely knows the state
