### ISSUE TITLE
[Plans] Cannot edit or view Plans

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4938]
#### Summary
Cannot edit or view Plans

#### Expected vs Current Behavior
1. Should be able to create a plan and view the contents
2. Should be able to view a previously created plan

#### Environment
* Open MCT Version: viper-openmct#2.0.1 / openmct#2.0.1
* System:
 - OS: macOS 11.6.3
 - CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
 - Memory: 204.44 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
* Binaries:
 - Node: 12.22.10 - ~/.nvm/versions/node/v12.22.10/bin/node
 - npm: 6.14.16 - ~/.nvm/versions/node/v12.22.10/bin/npm
* Languages:
 - Bash: 3.2.57 - /bin/bash
 - Go: 1.17.6 - /usr/local/bin/go
 - Perl: 5.30.2 - /usr/bin/perl
 - PHP: 7.3.29 - /usr/bin/php
 - Python: 2.7.16 - /usr/bin/python
 - Python3: 3.9.5 - /usr/local/bin/python3
 - Ruby: 2.6.3 - /usr/bin/ruby
* Browsers:
 - Brave Browser: 92.1.28.106
 - Chrome: 99.0.4844.51
 - Chrome Canary: 101.0.4943.0
 - Edge: 98.0.1108.43
 - Firefox: 88.0.1
 - Safari: 15.3

#### Impact Check List
- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Additional Information
``` console
TypeError: Cannot read properties of undefined (reading 'forEach')
    at i (util.js:39:36)
    at a.getPlanData (Plan.vue:162:29)
    at a.mounted (Plan.vue:95:14)
    at Ut (vue.min.js:6:11407)
    at Je (vue.min.js:6:25438)
    at Object.insert (vue.min.js:6:20517)
    at C (vue.min.js:6:60576)
    at _n.__patch__ (vue.min.js:6:61934)
    at _n.t._update (vue.min.js:6:34609)
    at _n.i (vue.min.js:6:68555)
Yt @ vue.min.js:6
Qt @ vue.min.js:6
Rt @ vue.min.js:6
Ut @ vue.min.js:6
Je @ vue.min.js:6
insert @ vue.min.js:6
C @ vue.min.js:6
(anonymous) @ vue.min.js:6
t._update @ vue.min.js:6
i @ vue.min.js:6
An.get @ vue.min.js:6
An @ vue.min.js:6
(anonymous) @ vue.min.js:6
_n.$mount @ vue.min.js:6
_n.$mount @ vue.min.js:6
e._init @ vue.min.js:6
_n @ vue.min.js:6
show @ PlanViewProvider.js:52
i.show @ ViewRegistry.js:95
updateView @ ObjectView.vue:260
show @ ObjectView.vue:305
a @ Browse.js:41
(anonymous) @ Browse.js:34
r.emit @ index.js:144
doParamsChange @ ApplicationRouter.js:350
handleLocationChange @ ApplicationRouter.js:377
setQueryString @ ApplicationRouter.js:411
updateParams @ ApplicationRouter.js:264
(anonymous) @ Browse.js:102
Promise.then (async)
(anonymous) @ Browse.js:67
(anonymous) @ Browse.js:20
doPathChange @ ApplicationRouter.js:318
handleLocationChange @ ApplicationRouter.js:372
navigate @ ApplicationRouter.js:136
navigateOrPreview @ ObjectLabel.vue:78
itemClick @ tree-item.vue:177
!click @ tree-item.vue?e18c:6
Ut @ vue.min.js:6
n @ vue.min.js:6
Vi.o._wrapper @ vue.min.js:6
mct-tree.vue:314 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'navigationPath')
    at a.openTreeItem (mct-tree.vue:314:41)
    at mct-tree.vue:432:29
    at async mct-tree.vue:429:53
```

**Comment by unlikelyzero** [comment]
This was incorrectly filed. Looking at old Plans when we don't support backwards compatibility
