### ISSUE TITLE
[Builds] All builds failing due to a broken transitive dependency in percy

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5029]
#### Summary
Output from `npm run test:e2e:ci`

```
#!/bin/bash -eo pipefail
npm run test:e2e:ci

> openmct@2.0.2-SNAPSHOT test:e2e:ci
> npx playwright test --config=e2e/playwright-ci.config.js --project=chrome smoke default condition timeConductor


Running 6 tests using 2 workers


Error: Cannot find module '/root/project/node_modules/@percy/sdk-utils/dist/index.js'

   at ../../node_modules/@percy/playwright/index.js:1

> 1 | const utils = require('@percy/sdk-utils');
    |               ^
  2 |
  3 | // Collect client and environment information
  4 | const sdkPkg = require('./package.json');

    at Object.<anonymous> (/root/project/node_modules/@percy/playwright/index.js:1:15)
::error ::Error: Cannot find module '/root/project/node_modules/@percy/sdk-utils/dist/index.js'%0A%0A   at ../../node_modules/@percy/playwright/index.js:1%0A%0A> 1 | const utils = require('@percy/sdk-utils');%0A    |               ^%0A  2 |%0A  3 | // Collect client and environment information%0A  4 | const sdkPkg = require('./package.json');%0A%0A    at Object.<anonymous> (/root/project/node_modules/@percy/playwright/index.js:1:15)


  6 skipped
::notice title=🎭 Playwright Run Summary::  6 skipped

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by unlikelyzero** [comment]
https://github.com/percy/cli/issues/856
