### ISSUE TITLE
[e2e] Snapshot bugs in  exportAsJSON tests

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5060]
#### Summary
https://app.circleci.com/pipelines/github/nasa/openmct/9777/workflows/52e28c8e-9678-42be-8898-ce0de15123dd/jobs/31411/tests#failed-test-0

```
plugins/plot/autoscale.e2e.spec.js:50:10 › ExportAsJSON › autoscale off causes no error from undefined user range 

    Error: Snapshot comparison failed:

    Expected: /root/project/test-results/plugins-plot-autoscale.e2e-ExportAsJSON-autoscale-off-causes-no-error-from-undefined-user-range-chrome/autoscale-canvas-prepan-expected.png
    Received: /root/project/test-results/plugins-plot-autoscale.e2e-ExportAsJSON-autoscale-off-causes-no-error-from-undefined-user-range-chrome/autoscale-canvas-prepan-actual.png
        Diff: /root/project/test-results/plugins-plot-autoscale.e2e-ExportAsJSON-autoscale-off-causes-no-error-from-undefined-user-range-chrome/autoscale-canvas-prepan-diff.png

      66 |             new Promise(r => setTimeout(r, 100))
      67 |                 .then(() => canvas.screenshot())
    > 68 |                 .then(shot => expect(shot).toMatchSnapshot('autoscale-canvas-prepan.png', { maxDiffPixels: 40 }))
         |                                            ^
      69 |         ]);
      70 |
      71 |         let errorCount = 0;

        at /root/project/e2e/tests/plugins/plot/autoscale.e2e.spec.js:68:44
        at async Promise.all (index 1)
        at /root/project/e2e/tests/plugins/plot/autoscale.e2e.spec.js:64:9
```

**Comment by unlikelyzero** [comment]
Testing Notes
Run `npm run test:e2e:full`

**Comment by akhenry** [comment]
Verified fixed, though [there are other e2e tests failing right now](https://github.com/nasa/openmct/issues/5112).
