### ISSUE TITLE
Tests aren't using source maps

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#5211]
#### Summary
The tests aren't properly using source maps, which means we aren't getting proper line numbers in the source. This makes it difficult to debug tests.

#### Expected vs Current Behavior
The tests should be showing proper line numbers. Here's a nominal behavior:
```
1) uses source maps properly
     The Annotation API
     Error: Do source maps works
    at AnnotationAPI.fail (webpack-internal:///./src/api/annotation/AnnotationAPI.js:214:11)
    at UserContext.eval (webpack-internal:///./src/api/annotation/AnnotationAPISpec.js:95:35)
    at <Jasmine>
```

Here's the current behavior:
```
1) uses source maps properly
     The Annotation API
     Error: Do source maps works
    at AnnotationAPI.fail (/var/folders/v5/1_75xn0x1_v5_md8t9vtb1jr0000gn/T/_karma_webpack_568129/commons.js:47755:11)
    at UserContext.<anonymous> (/var/folders/v5/1_75xn0x1_v5_md8t9vtb1jr0000gn/T/_karma_webpack_568129/commons.js:286364:35)
    at <Jasmine>
```

#### Steps to Reproduce
1. Add a failing test, e.g. `expect(false).toBe(true)`
2. run `npm test`
3. see bad behavior

#### Environment

* Open MCT Version: master
* Deployment Type: dev
```
## System:
 - OS: macOS 12.3.1
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 2.16 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
 - npm: 8.9.0 - ~/.nvm/versions/node/v14.19.1/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
 - Java: 11.0.11 - /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javac
 - Perl: 5.34.0 - /usr/local/bin/perl
 - Protoc: 3.19.4 - /usr/local/bin/protoc
 - Python: 2.7.18 - /Users/scott/.pyenv/shims/python
 - Python3: 3.9.12 - /usr/local/bin/python3
 - R: 4.1.0 - /usr/local/bin/R
 - Ruby: 2.6.8 - /usr/bin/ruby
## Browsers:
 - Chrome: 101.0.4951.64
 - Firefox: 100.0
 - Safari: 15.4
## npmPackages:
 - @babel/eslint-parser: 7.16.3 => 7.16.3 
 - @braintree/sanitize-url: 6.0.0 => 6.0.0 
 - @percy/cli: 1.0.4 => 1.0.4 
 - @percy/playwright: 1.0.3 => 1.0.3 
 - @playwright/test: 1.21.1 => 1.21.1 
 - @types/eventemitter3: ^1.0.0 => 1.2.0 
 - @types/jasmine: ^4.0.1 => 4.0.3 
 - @types/karma: ^6.3.2 => 6.3.3 
 - @types/lodash: ^4.14.178 => 4.14.182 
 - @types/mocha: ^9.1.0 => 9.1.1 
 - allure-playwright: 2.0.0-beta.15 => 2.0.0-beta.15 
 - babel-loader: 8.2.3 => 8.2.3 
 - babel-plugin-istanbul: 6.1.1 => 6.1.1 
 - comma-separated-values: 3.6.4 => 3.6.4 
 - copy-webpack-plugin: 10.2.0 => 10.2.0 
 - cross-env: 7.0.3 => 7.0.3 
 - css-loader: 4.0.0 => 4.0.0 
 - d3-axis: 3.0.0 => 3.0.0 
 - d3-scale: 3.3.0 => 3.3.0 
 - d3-selection: 3.0.0 => 3.0.0 
 - eslint: 8.13.0 => 8.13.0 
 - eslint-plugin-compat: 4.0.2 => 4.0.2 
 - eslint-plugin-playwright: 0.9.0 => 0.9.0 
 - eslint-plugin-vue: 8.5.0 => 8.5.0 
 - eslint-plugin-you-dont-need-lodash-underscore: 6.12.0 => 6.12.0 
 - eventemitter3: 1.2.0 => 1.2.0 
 - exports-loader: 0.7.0 => 0.7.0 
 - express: 4.13.1 => 4.13.1 
 - file-saver: 2.0.5 => 2.0.5 
 - git-rev-sync: 3.0.2 => 3.0.2 
 - html2canvas: 1.4.1 => 1.4.1 
 - imports-loader: 0.8.0 => 0.8.0 
 - jasmine-core: 4.0.1 => 4.0.1 
 - jsdoc: 3.5.5 => 3.5.5 
 - karma: 6.3.18 => 6.3.18 
 - karma-chrome-launcher: 3.1.1 => 3.1.1 
 - karma-cli: 2.0.0 => 2.0.0 
 - karma-coverage: 2.2.0 => 2.2.0 
 - karma-coverage-istanbul-reporter: 3.0.3 => 3.0.3 
 - karma-firefox-launcher: 2.1.2 => 2.1.2 
 - karma-jasmine: 4.0.1 => 4.0.1 
 - karma-junit-reporter: 2.0.1 => 2.0.1 
 - karma-sourcemap-loader: 0.3.8 => 0.3.8 
 - karma-spec-reporter: 0.0.34 => 0.0.34 
 - karma-webpack: 5.0.0 => 5.0.0 
 - lighthouse: 9.5.0 => 9.5.0 
 - location-bar: 3.0.1 => 3.0.1 
 - lodash: 4.17.21 => 4.17.21 
 - mini-css-extract-plugin: 2.6.0 => 2.6.0 
 - moment: 2.29.3 => 2.29.3 
 - moment-duration-format: 2.3.2 => 2.3.2 
 - moment-timezone: 0.5.34 => 0.5.34 
 - node-bourbon: 4.2.3 => 4.2.3 
 - painterro: 1.2.56 => 1.2.56 
 - plotly.js-basic-dist: 2.12.0 => 2.12.0 
 - plotly.js-gl2d-dist: 2.12.0 => 2.12.0 
 - printj: 1.3.1 => 1.3.1 
 - request: 2.88.2 => 2.88.2 
 - resolve-url-loader: 5.0.0 => 5.0.0 
 - sass: 1.49.9 => 1.49.9 
 - sass-loader: 12.6.0 => 12.6.0 
 - sinon: 13.0.1 => 13.0.1 
 - style-loader: ^1.0.1 => 1.3.0 
 - uuid: 3.3.3 => 3.3.3 
 - vue: 2.6.14 => 2.6.14 
 - vue-eslint-parser: 8.3.0 => 8.3.0 
 - vue-loader: 15.9.8 => 15.9.8 
 - vue-template-compiler: 2.6.14 => 2.6.14 
 - webpack: 5.68.0 => 5.68.0 
 - webpack-cli: 4.9.2 => 4.9.2 
 - webpack-dev-middleware: 5.3.1 => 5.3.1 
 - webpack-hot-middleware: 2.25.1 => 2.25.1 
 - webpack-merge: 5.8.0 => 5.8.0 
 - zepto: 1.2.0 => 1.2.0

#### Impact Check List
<!--- Please select from the following options -->
- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [X] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?

#### Additional Information
This PR seems to have caused the behavior:
https://github.com/nasa/openmct/pull/4649
specifically the move to the new webpack config:
https://github.com/nasa/openmct/pull/4649/files#diff-25bdb46a5428d318648ec9eb46a99c0268d8c96b672c46e2247a685bc3e384fbR26
Switching the `karma.conf.js` to using:
`const webpackConfig = require('./webpack.dev.js');`
resolves the problem. I suspect the istanbul code coverage tool is interfering with the source mapping.

**Comment by unlikelyzero** [comment]
Adding blocker since this fundamentally breaks our ability to fix test failure

**Comment by akhenry** [comment]
Verified fixed for test spec classes, and partially fixed for Open MCT core code. Test specs now give accurate file and function names. Line numbers are inaccurate for Open MCT core code, probably due to injected line coverage code.

**Comment by scottbell** [comment]
Was able to replicate:
```
1) can create annotations
     The Annotation API Creation
     TypeError: Cannot read properties of undefined (reading 'red')
    at AnnotationAPI.create (/var/folders/v5/1_75xn0x1_v5_md8t9vtb1jr0000gn/T/_karma_webpack_263331/commons.js:369464:17)
    at UserContext.<anonymous> (/var/folders/v5/1_75xn0x1_v5_md8t9vtb1jr0000gn/T/_karma_webpack_263331/commons.js:905069:63)
    at <Jasmine>
```
investigating...

**Comment by unlikelyzero** [comment]
@scottbell you might want to try to run the tests with `nyc` and use a .nycrc config https://github.com/nasa/openmct/tree/nyc-file

**Comment by scottbell** [comment]
> @scottbell you might want to try to run the tests with `nyc` and use a .nycrc config https://github.com/nasa/openmct/tree/nyc-file

Are we switching to nyc?

**Comment by unlikelyzero** [comment]
> > @scottbell you might want to try to run the tests with `nyc` and use a .nycrc config https://github.com/nasa/openmct/tree/nyc-file
> 
> Are we switching to nyc?

If it gets us off of karma specific tooling, I think we should investigate

**Comment by ozyx** [comment]
Verified 8/11/22:

I am able to see the origin of the failure (lineNumber,position) when running `npm run test` locally
