### ISSUE TITLE
[Unit tests] Update unit tests to match new describe() and it() syntax checks

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5405]
#### Summary
karma-jasmine-5.1.0 updated syntax checks after giving us deprecation warnings for months. The following tests are failing

```bash
Chrome Headless 103.0.5060.53 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Error: describe with no children (describe() or it()): the plugin when invoked
      at <Jasmine>
      at /tmp/_karma_webpack_276262/commons.js:929829:5
      at <Jasmine>
      at ./src/plugins/viewDatumAction/pluginSpec.js (/tmp/_karma_webpack_276262/commons.js:929777:1)
      at __webpack_require__ (/tmp/_karma_webpack_276262/runtime.js:23:42)
      at webpackContext (/tmp/_karma_webpack_276262/commons.js:931150:9)
      at Array.forEach (<anonymous>)
Chrome Headless 103.0.5060.53 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Error: describe with no children (describe() or it()): the plugin when invoked
      at <Jasmine>
      at /tmp/_karma_webpack_276262/commons.js:929829:5
      at <Jasmine>
      at ./src/plugins/viewDatumAction/pluginSpec.js (/tmp/_karma_webpack_276262/commons.js:929777:1)
      at __webpack_require__ (/tmp/_karma_webpack_276262/runtime.js:23:42)
      at webpackContext (/tmp/_karma_webpack_276262/commons.js:931150:9)
      at Array.forEach (<anonymous>)
```

Update:
- [ ] Fix all failing tests associated with the new check
- [ ] Update karma-jasmine-5.1.0 dependency

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 08/02/22 - All unit tests pass when running `npm run test`
