### ISSUE TITLE
Unhandled TypeError while using Grand Search

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5639]
#### Summary

![image](https://user-images.githubusercontent.com/9259993/183754447-03f12ab9-7e04-463e-9ba2-6ae350967aa5.png)

#### Expected vs Current Behavior

Expected: no unhandled TypeErrors

#### Steps to Reproduce

1. Type in a search term to the grand search
2. Before the search has completed, delete the term character-by-character
3. Notice errors thrown

#### Environment

Seen during Testathon 8/9/22

```
Version: 2.0.7
Build Date: Thu Aug 04 2022 12:33:07 GMT-0700 (Pacific Daylight Time)
Revision: 15a0a872512556792cac6a8f8cd201a350222312
Branch: release/2.0.7
```

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
@ozyx I'm able to replicate one of the errors:
```
Error searching DOMException: Failed to execute 'fetch' on 'Window': The user aborted a request.
    at CouchObjectProvider.getObjectsByFilter (webpack-internal:///./src/plugins/persistence/couch/CouchObjectProvider.js:433:32)
    at CouchSearchProvider.searchForTags (webpack-internal:///./src/plugins/persistence/couch/CouchSearchProvider.js:150:41)
    at CouchSearchProvider.search (webpack-internal:///./src/plugins/persistence/couch/CouchSearchProvider.js:53:25)
    at eval (webpack-internal:///./src/api/objects/ObjectAPI.js:292:39)
    at Array.map (<anonymous>)
    at ObjectAPI.search (webpack-internal:///./src/api/objects/ObjectAPI.js:292:14)
    at AnnotationAPI.searchForTags (webpack-internal:///./src/api/annotation/AnnotationAPI.js:284:71)
    at VueComponent.getSearchResults (webpack-internal:///./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/ui/layout/search/GrandSearch.vue?vue&type=script&lang=js&:125:78)
    at async VueComponent.searchEverything (webpack-internal:///./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/ui/layout/search/GrandSearch.vue?vue&type=script&lang=js&:91:
```

but not the `identifier` one, though it's pretty clear in the `getPathsForObjects` function where it's happening:
`const keyStringForObject = this.openmct.objects.makeKeyString(domainObject.identifier);`

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 9/12/22

I still see the items canceled in the network tab, but the errors are gone in console. Nice!

**Comment by ozyx** [comment]
Verified Testathon 9/12/22

Not seeing any console errors anymore
