### ISSUE TITLE
rollup file error java code not known

### ISSUE THREAD

**Issue by shaynababe** [nasa/openmct#6575]
#### Summary

not JAVA code
```bash
/api/forms/components/FormRow.vue (imported by "src/api/forms/components/FormProperties.vue")
(!) "this" has been rewritten to "undefined"
https://rollupjs.org/troubleshooting/#error-this-is-undefined
src/plugins/autoflow/AutoflowTabularPluginSpec.js
353:                 for (let height = 0; height < rowHeight * count * 2; height += rowHeight / 2) {
354:                     // eslint-disable-next-line no-invalid-this
355:                     promiseChain = promiseChain.then(setHeight.bind(this, height));
                                                                         ^
356:                 }
[!] RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/api/indicators/res/indicator-template.html (1:0)
1: <div class="c-indicator c-indicator--clickable c-indicator--simple" title="">
   ^
2:     <span class="label js-indicator-text c-indicator__label"></span>
3: </div>
    at error (/usr/lib/node_modules/rollup/dist/shared/rollup.js:274:30)
    at Module.error (/usr/lib/node_modules/rollup/dist/shared/rollup.js:13820:16)
    at Module.tryParse (/usr/lib/node_modules/rollup/dist/shared/rollup.js:14497:25)
    at Module.setSource (/usr/lib/node_modules/rollup/dist/shared/rollup.js:14107:39)
    at ModuleLoader.addModuleSource (/usr/lib/node_modules/rollup/dist/shared/rollup.js:24072:20)


(base) z@spin7:~/code/openmct$ 

```

**Comment by shaynababe** [comment]
```bash
                for (let height = 0; height < rowHeight * count * 2; height += rowHeight / 2) {
                    // eslint-disable-next-line no-invalid-this
                    promiseChain = promiseChain.then(setHeight.bind(this, height));
                }
```

**Comment by shaynababe** [comment]
new rollup plug in is working
