### ISSUE TITLE
rollup vue file errors out of bounds Conditions,  not exported by, but imported by error pi /telemetryTable/

### ISSUE THREAD

**Issue by shaynababe** [nasa/openmct#6576]
#### Summary

vue files error Plugin conditions and src/plugins/telemetryTable/components/table-configuration.vue 
[Vueindex.html.txt](https://github.com/nasa/openmct/files/11184039/Vueindex.html.txt)
two type 
https://drive.google.com/file/d/1aTXHhUVDLDNioUjGk42Ube61T-eeTKVP/view?usp=share_link
gzip archive is bundle
```bash
node_modules/.pnpm/d3-interpolate@2.0.1/node_modules/d3-interpolate/src/value.js -> node_modules/.pnpm/d3-interpolate@2.0.1/node_modules/d3-interpolate/src/array.js -> node_modules/.pnpm/d3-interpolate@2.0.1/node_modules/d3-interpolate/src/value.js
node_modules/.pnpm/d3-interpolate@2.0.1/node_modules/d3-interpolate/src/value.js -> node_modules/.pnpm/d3-interpolate@2.0.1/node_modules/d3-interpolate/src/object.js -> node_modules/.pnpm/d3-interpolate@2.0.1/node_modules/d3-interpolate/src/value.js
node_modules/.pnpm/d3-selection@3.0.0/node_modules/d3-selection/src/selection/index.js -> node_modules/.pnpm/d3-selection@3.0.0/node_modules/d3-selection/src/selection/select.js -> node_modules/.pnpm/d3-selection@3.0.0/node_modules/d3-selection/src/selection/index.js
...and 7 more
[!] RollupError: "default" is not exported by "src/plugins/telemetryTable/TelemetryTableColumn.js", imported by "src/plugins/telemetryTable/components/table-configuration.vue".
https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module
src/plugins/telemetryTable/components/table-configuration.vue (71:7)
69: 
70: <script>
71: import TelemetryTableColumn from '../TelemetryTableColumn';
           ^
72: import TelemetryTableUnitColumn from '../TelemetryTableUnitColumn';
    at error (/usr/lib/node_modules/rollup/dist/shared/rollup.js:274:30)
    at Module.error (/usr/lib/node_modules/rollup/dist/shared/rollup.js:13820:16)
    at Module.traceVariable (/usr/lib/node_modules/rollup/dist/shared/rollup.js:14205:29)
    at ModuleScope.findVariable (/usr/lib/node_modules/rollup/dist/shared/rollup.js:12708:39)
    at FunctionScope.findVariable (/usr/lib/node_modules/rollup/dist/shared/rollup.js:7451:38)
    at ChildScope.findVariable (/usr/lib/node_modules/rollup/dist/shared/rollup.js:7451:38)
    at ReturnValueScope.findVariable (/usr/lib/node_modules/rollup/dist/shared/rollup.js:7451:38)
    at ChildScope.findVariable (/usr/lib/node_modules/rollup/dist/shared/rollup.js:7451:38)
    at Identifier.bind (/usr/lib/node_modules/rollup/dist/shared/rollup.js:8601:40)
    at NewExpression.bind (/usr/lib/node_modules/rollup/dist/shared/rollup.js:6247:23)

[!] (plugin vue2) Error: end is out of bounds
src/condition/components/CurrentOutput.vue
    at MagicString.update (/home/z/code/openmct/node_modules/.pnpm/magic-string@0.30.0/node_modules/magic-string/dist/magic-string.cjs.js:693:41)
    at MagicString.overwrite (/home/z/code/openmct/node_modules/.pnpm/magic-string@0.30.0/node_modules/magic-string/dist/magic-string.cjs.js:684:15)
    at vueTransform (/home/z/code/openmct/node_modules/.pnpm/rollup-plugin-vue2@0.8.1/node_modules/rollup-plugin-vue2/dist/rollup-plugin-vue2.common.js:83:7)
    at Object.transform (/home/z/code/openmct/node_modules/.pnpm/rollup-plugin-vue2@0.8.1/node_modules/rollup-plugin-vue2/dist/rollup-plugin-vue2.common.js:40:14)
    at /usr/lib/node_modules/rollup/dist/shared/rollup.js:24893:40


```

**Comment by shaynababe** [comment]
A new test is ongong . for the git src tree Node is being used for the check
Glob root dir is scr and the openmct.js is the enter point it has some errors but this is expected

This is something to do with one of the files
