### ISSUE TITLE
[examples] The image data source shows errors and no data in scrolling view

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#703]
Error appears to be because the telemetry source is using an unknown domain value format 'timestamp'. Previously this issue may have been suppressed, but a1d765f2712a83d6026a852d34c2041f7a5c301d introduced an error for unknown formats.

Suggest updating examples/imagery to use 'utc' instead of 'timestamp'
```
Error: FormatProvider: No format found for timestamp
    at FormatProvider.getFormat (http://localhost:8080/platform/commonUI/formats/src/FormatProvider.js:107:19)
    at TelemetryFormatter.formatDomainValue (http://localhost:8080/platform/telemetry/src/TelemetryFormatter.js:61:40)
    at DomainColumn.getValue (http://localhost:8080/platform/features/scrolling/src/DomainColumn.js:56:47)
```

**Comment by akhenry** [comment]
Scrolling list has been removed. Appears to work in new realtime tables.

**Comment by VWoeltjen** [comment]
Verified working in real-time tables, testathon 20160509
