### ISSUE TITLE
[Timelines] Creating a new timeline results in repeated error messages to the console

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#717]
To recreate, simply create a new timeline from the create button. The error message below will begin appearing in the javascript console.

```
TypeError: Cannot read property 'timestamp' of undefined
    at i (http://localhost:9080/static/main.js:19:19168)
    at s (http://localhost:9080/static/main.js:19:19286)
    at Object.a [as getDuration] (http://localhost:9080/static/main.js:19:19311)
    at fn (eval at <anonymous> (http://localhost:9080/static/main.js:4:30025), <anonymous>:4:614)
    at Object.get (http://localhost:9080/static/main.js:3:11768)
    at p.$digest (http://localhost:9080/static/main.js:3:20074)
    at p.$apply (http://localhost:9080/static/main.js:3:21755)
    at http://localhost:9080/static/main.js:3:2978 
```

**Comment by VWoeltjen** [comment]
Think this may be caused by uninitialized state in the Timeline model. Pre-NEM, the Create dialog was always seen first, meaning that any required fields would get some input. (If so, that's an interesting consequence of NEM to be aware of - domain object properties must now have defaults.)

**Comment by VWoeltjen** [comment]
Verified testathon 20160401
