### ISSUE TITLE
[Tables] Error shown in javascript console when first row is added to a realtime table

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#742]
```
TypeError: Cannot read property '1' of undefined
    at MCTTableController.newRow (http://localhost:8080/platform/features/table/src/controllers/MCTTableController.js:102:39)
    at n.$broadcast (http://localhost:8080/bower_components/angular/angular.min.js:135:398)
    at http://localhost:8080/platform/features/table/src/controllers/RTTelemetryTableController.js:96:41
```
There's a potential data loss issue here, as first streaming telemetry update does not appear in the table due to error.

**Comment by akhenry** [comment]
Removed critical label, issue was benign. No data loss, just an error in the log. Missing first record is issue in the example data source.

**Comment by charlesh88** [comment]
Testathon 031516
Verified fixed in Linux Chrome.
