### ISSUE TITLE
`renderWhenVisible` console error on quick navigation away from complex display

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#7711]
#### Summary
Related to #7408
Console errors regarding `renderWhenVisible` observers are thrown when navigating away from a complex display.

#### Expected vs Current Behavior
no console errors

#### Steps to Reproduce
1. Open browser console
2. Navigate to a complex display (bug discovered using a tabbed view `eager load tabs === true`)
3. Navigate away quickly
4. Repeat steps 2-3 (and set network throttling if needed) until console error is thrown

#### Environment

* Open MCT Version: 4.0.0-next (b3d3465734947050bd2223f824f91e2b34893a14)
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
```openmct.js:2 Uncaught TypeError: Cannot read properties of null (reading 'observe')
    at Hx.renderWhenVisible (openmct.js:2:3482011)
    at Proxy.scheduleDraw (openmct.js:2:3694531)
    at Proxy.handleWindowResize (openmct.js:2:3686605)
    at b (openmct.js:2:374853)
    at M (openmct.js:2:375060)
    at f (openmct.js:2:374962)

**Comment by davetsay** [comment]
added permalink to description, https://github.com/nasa/openmct/blob/17bc6cb7225026d77375bcc9e9ea299d013b66c0/src/utils/visibility/VisibilityObserver.js#L82
