### ISSUE TITLE
The HTML example doesn't work if I import the dist openmct.js file via node_modules

### ISSUE THREAD

**Issue by zachsa** [nasa/openmct#7719]
The basic HTML example doesn't work if I import the dist openmct.js file via node_modules:

```html
<!-- index.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Open MCT</title>
    <script src="./node_modules/openmct/dist/openmct.js"></script>
</head>
<body>
    <script>
      openmct.install(openmct.plugins.LocalStorage());
      openmct.install(openmct.plugins.MyItems());
      openmct.install(openmct.plugins.UTCTimeSystem());
      openmct.start();
    </script>
</body>
</html>
```

Loading that file via a web-server (`npx http-server -c-1`) I get the following error from the `openmct.start()` statement:

```txt
openmct.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'key')
    at d.setTimeApiFromUrl (openmct.js:2:2636125)
    at d.updateTimeSettings (openmct.js:2:2635705)
    at d.initialize (openmct.js:2:2635136)
    at o.emit (openmct.js:2:337020)
    at Proxy.<anonymous> (openmct.js:2:2492616)
```

I'm not sure if this approach is supported - I would prefer to work with `openmct` via the node_modules folder as a dep if possible, please let me know if this error is expected or if it is indeed a bug!

To reproduce:

```
cd some/folder
npm install openmct
touch index.html
// copy the contents of the html file above into this file
npx http-server -c-1 // And navigate to the url - that loads the index.html file and the error occurs
```

**Comment by ozyx** [comment]
Hi! Could you let us know a little more about what you're trying to do? This repo is set up for development of core Open MCT only, meaning that in order to run it locally, you must use the webpack dev server (`npm start`).

If you're trying to develop a plugin for Open MCT, you can take a look at our project template-- [openmct-hello](https://github.com/nasa/openmct-hello). This is a work-in-progress, but should have everything you need to get started.

If you're trying to use Open MCT as a dependency for another project, we will have an example template for this in the coming weeks.

**Comment by zachsa** [comment]
Hi @ozyx. Thank you for such a quick response.

I am aiming to develop a plugin with openmct installed a dependency (exactly as is done in the openmct-hello repo). Thank you for the link.

I thought I would be able to use the `dist/openmct.js` script imported via jsdelivr or similar when developing a plugin. Is that possible? I actually wanted to avoid server bundling via webpack and just import the plugin code. But I realize now that if my plugin includes any UI components that it would need to be bundled anyway.

However, I was expecting to get the baseic Open MCT UI from my example above (i.e. by importing dist/openmct.js via jsdelivr or something similar). Out of interest, why doesn't that work?

**Comment by ozyx** [comment]
@zachsa Which version are you using? Could you try installing from source and let us know if that fixes it?

You can specify the version in your package.json like so:
```json
"openmct": "nasa/openmct"
```

**Comment by zachsa** [comment]
Thank you for the reply @ozyx. I moved the script tag to the header, and added the div#app tag to the body.. and it seems to work now:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Open MCT</title>
    <script src="/node_modules/openmct/dist/openmct.js"></script>
    <script defer>
      document.addEventListener("DOMContentLoaded", function () {
        openmct.setAssetPath("node_modules/openmct/dist");
        openmct.install(openmct.plugins.LocalStorage());
        openmct.install(openmct.plugins.MyItems());
        openmct.install(openmct.plugins.UTCTimeSystem());
        openmct.time.setClock("local", { start: -15 * 60 * 1000, end: 0 });
        openmct.time.getTimeSystem("utc");
        openmct.install(openmct.plugins.Espresso());
        openmct.start();
      });
    </script>
  </head>
  <body>
    <body>
      <div id="app"></div>
    </body>
  </body>
</html>
```

Although I notice that if I go to the root path I get a console error:

```sh
npx http-server -c-1
```

It seems like sometimes when I navigate to `http://localhost:8080` I get a console error (not all the time though):

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'key')
    at d.setUrlFromTimeApi (openmct.js:2:2637140)
    at d.updateTimeSettings (openmct.js:2:2635773)
    at d.initialize (openmct.js:2:2635136)
    at o.emit (openmct.js:2:337020)
    at Proxy.<anonymous> (openmct.js:2:2492616)
```

![image](https://github.com/nasa/openmct/assets/6336500/cf3f6dd4-372c-4730-bce4-85a988907c71)
