### ISSUE TITLE
[Representation] Exception in InfoButtonGesture

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#948]
Sometimes see an error on console for InfoButtonGesture, when it attempts to use `element.scope()` during constructor call:

```
angular.js:12416TypeError: Cannot read property '$on' of undefined
    at new InfoGestureButton (http://localhost:8080/platform/commonUI/inspect/src/gestures/InfoButtonGesture.js:99:39)
    at InfoGestureButton.Constructor (http://localhost:8080/platform/framework/src/resolve/ExtensionResolver.js:70:37)
    at new InnerConstructor (http://localhost:8080/platform/framework/src/register/PartialConstructor.js:57:44)
    at http://localhost:8080/platform/representation/src/gestures/GestureProvider.js:101:28
    at Array.map (native)
    at GestureProvider.attachGestures (http://localhost:8080/platform/representation/src/gestures/GestureProvider.js:100:20)
    at GestureRepresenter.represent (http://localhost:8080/platform/representation/src/gestures/GestureRepresenter.js:52:54)
    at http://localhost:8080/platform/representation/src/MCTRepresentation.js:218:41
    at Array.forEach (native)
    at refresh (http://localhost:8080/platform/representation/src/MCTRepresentation.js:217:44) <mct-representation class="desktop-hide ng-isolate-scope" key="'info-button'" mct-object="domainObject">
```

This may be a side-effect of #942. In any event, the `$on` in question is not useful; the `$destroy` event is listened to by `mct-representation` so this behavior only needs to be handled in the `destroy` method of the gesture itself.

**Comment by VWoeltjen** [comment]
Verified testathon 2016-06-16
